//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePowerCCBApi.ePowerBridge {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datos", Namespace="http://schemas.datacontract.org/2004/07/EpowerWSManagement")]
    [System.SerializableAttribute()]
    public partial class Datos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorDecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoContenido {
            get {
                return this.TipoContenidoField;
            }
            set {
                if ((this.TipoContenidoField.Equals(value) != true)) {
                    this.TipoContenidoField = value;
                    this.RaisePropertyChanged("TipoContenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorDec {
            get {
                return this.ValorDecField;
            }
            set {
                if ((this.ValorDecField.Equals(value) != true)) {
                    this.ValorDecField = value;
                    this.RaisePropertyChanged("ValorDec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorString {
            get {
                return this.ValorStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorStringField, value) != true)) {
                    this.ValorStringField = value;
                    this.RaisePropertyChanged("ValorString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contenido", Namespace="http://schemas.datacontract.org/2004/07/EpowerWSManagement")]
    [System.SerializableAttribute()]
    public partial class Contenido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinarioBase64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionBinarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreBinarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TabNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinarioBase64 {
            get {
                return this.BinarioBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.BinarioBase64Field, value) != true)) {
                    this.BinarioBase64Field = value;
                    this.RaisePropertyChanged("BinarioBase64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtensionBinario {
            get {
                return this.ExtensionBinarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionBinarioField, value) != true)) {
                    this.ExtensionBinarioField = value;
                    this.RaisePropertyChanged("ExtensionBinario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreBinario {
            get {
                return this.NombreBinarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreBinarioField, value) != true)) {
                    this.NombreBinarioField = value;
                    this.RaisePropertyChanged("NombreBinario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TabName {
            get {
                return this.TabNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TabNameField, value) != true)) {
                    this.TabNameField = value;
                    this.RaisePropertyChanged("TabName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoAccion", Namespace="http://schemas.datacontract.org/2004/07/EpowerWSManagement")]
    [System.SerializableAttribute()]
    public partial class ResultadoAccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://schemas.datacontract.org/2004/07/EpowerWSManagement")]
    [System.SerializableAttribute()]
    public partial class Resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePowerCCBApi.ePowerBridge.ResultadoCont[] ItemsContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePowerCCBApi.ePowerBridge.ResultDetalle[] ItemsDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int docIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePowerCCBApi.ePowerBridge.ResultadoCont[] ItemsContenido {
            get {
                return this.ItemsContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsContenidoField, value) != true)) {
                    this.ItemsContenidoField = value;
                    this.RaisePropertyChanged("ItemsContenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePowerCCBApi.ePowerBridge.ResultDetalle[] ItemsDetalle {
            get {
                return this.ItemsDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsDetalleField, value) != true)) {
                    this.ItemsDetalleField = value;
                    this.RaisePropertyChanged("ItemsDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int docId {
            get {
                return this.docIdField;
            }
            set {
                if ((this.docIdField.Equals(value) != true)) {
                    this.docIdField = value;
                    this.RaisePropertyChanged("docId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoCont", Namespace="http://schemas.datacontract.org/2004/07/EpowerWSManagement")]
    [System.SerializableAttribute()]
    public partial class ResultadoCont : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cejillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string etiquetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rutaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cejilla {
            get {
                return this.cejillaField;
            }
            set {
                if ((object.ReferenceEquals(this.cejillaField, value) != true)) {
                    this.cejillaField = value;
                    this.RaisePropertyChanged("cejilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                if ((object.ReferenceEquals(this.etiquetaField, value) != true)) {
                    this.etiquetaField = value;
                    this.RaisePropertyChanged("etiqueta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruta {
            get {
                return this.rutaField;
            }
            set {
                if ((object.ReferenceEquals(this.rutaField, value) != true)) {
                    this.rutaField = value;
                    this.RaisePropertyChanged("ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDetalle", Namespace="http://schemas.datacontract.org/2004/07/EpowerWSManagement")]
    [System.SerializableAttribute()]
    public partial class ResultDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string camposField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valoresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string campos {
            get {
                return this.camposField;
            }
            set {
                if ((object.ReferenceEquals(this.camposField, value) != true)) {
                    this.camposField = value;
                    this.RaisePropertyChanged("campos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valores {
            get {
                return this.valoresField;
            }
            set {
                if ((object.ReferenceEquals(this.valoresField, value) != true)) {
                    this.valoresField = value;
                    this.RaisePropertyChanged("valores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ePowerBridge.IServicioEpower")]
    public interface IServicioEpower {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/SaveDocument", ReplyAction="http://tempuri.org/IServicioEpower/SaveDocumentResponse")]
        ePowerCCBApi.ePowerBridge.ResultadoAccion SaveDocument(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data, ePowerCCBApi.ePowerBridge.Datos[] dataSet, ePowerCCBApi.ePowerBridge.Contenido[] contenido, int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/SaveDocument", ReplyAction="http://tempuri.org/IServicioEpower/SaveDocumentResponse")]
        System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.ResultadoAccion> SaveDocumentAsync(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data, ePowerCCBApi.ePowerBridge.Datos[] dataSet, ePowerCCBApi.ePowerBridge.Contenido[] contenido, int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/SaveDocumentTest", ReplyAction="http://tempuri.org/IServicioEpower/SaveDocumentTestResponse")]
        ePowerCCBApi.ePowerBridge.ResultadoAccion SaveDocumentTest(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data, ePowerCCBApi.ePowerBridge.Datos[] dataSet, ePowerCCBApi.ePowerBridge.Contenido[] contenido, int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/SaveDocumentTest", ReplyAction="http://tempuri.org/IServicioEpower/SaveDocumentTestResponse")]
        System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.ResultadoAccion> SaveDocumentTestAsync(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data, ePowerCCBApi.ePowerBridge.Datos[] dataSet, ePowerCCBApi.ePowerBridge.Contenido[] contenido, int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/LoginePower", ReplyAction="http://tempuri.org/IServicioEpower/LoginePowerResponse")]
        ePowerCCBApi.ePowerBridge.ResultadoAccion LoginePower(string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/LoginePower", ReplyAction="http://tempuri.org/IServicioEpower/LoginePowerResponse")]
        System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.ResultadoAccion> LoginePowerAsync(string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/LoginePowerTest", ReplyAction="http://tempuri.org/IServicioEpower/LoginePowerTestResponse")]
        ePowerCCBApi.ePowerBridge.ResultadoAccion LoginePowerTest(string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/LoginePowerTest", ReplyAction="http://tempuri.org/IServicioEpower/LoginePowerTestResponse")]
        System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.ResultadoAccion> LoginePowerTestAsync(string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/QueryDocument", ReplyAction="http://tempuri.org/IServicioEpower/QueryDocumentResponse")]
        ePowerCCBApi.ePowerBridge.Resultado[] QueryDocument(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/QueryDocument", ReplyAction="http://tempuri.org/IServicioEpower/QueryDocumentResponse")]
        System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.Resultado[]> QueryDocumentAsync(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/QueryDocumentTest", ReplyAction="http://tempuri.org/IServicioEpower/QueryDocumentTestResponse")]
        ePowerCCBApi.ePowerBridge.Resultado[] QueryDocumentTest(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEpower/QueryDocumentTest", ReplyAction="http://tempuri.org/IServicioEpower/QueryDocumentTestResponse")]
        System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.Resultado[]> QueryDocumentTestAsync(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEpowerChannel : ePowerCCBApi.ePowerBridge.IServicioEpower, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEpowerClient : System.ServiceModel.ClientBase<ePowerCCBApi.ePowerBridge.IServicioEpower>, ePowerCCBApi.ePowerBridge.IServicioEpower {
        
        public ServicioEpowerClient() {
        }
        
        public ServicioEpowerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEpowerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEpowerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEpowerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ePowerCCBApi.ePowerBridge.ResultadoAccion SaveDocument(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data, ePowerCCBApi.ePowerBridge.Datos[] dataSet, ePowerCCBApi.ePowerBridge.Contenido[] contenido, int pos) {
            return base.Channel.SaveDocument(User, Password, appId, tipeId, queryId, data, dataSet, contenido, pos);
        }
        
        public System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.ResultadoAccion> SaveDocumentAsync(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data, ePowerCCBApi.ePowerBridge.Datos[] dataSet, ePowerCCBApi.ePowerBridge.Contenido[] contenido, int pos) {
            return base.Channel.SaveDocumentAsync(User, Password, appId, tipeId, queryId, data, dataSet, contenido, pos);
        }
        
        public ePowerCCBApi.ePowerBridge.ResultadoAccion SaveDocumentTest(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data, ePowerCCBApi.ePowerBridge.Datos[] dataSet, ePowerCCBApi.ePowerBridge.Contenido[] contenido, int pos) {
            return base.Channel.SaveDocumentTest(User, Password, appId, tipeId, queryId, data, dataSet, contenido, pos);
        }
        
        public System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.ResultadoAccion> SaveDocumentTestAsync(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data, ePowerCCBApi.ePowerBridge.Datos[] dataSet, ePowerCCBApi.ePowerBridge.Contenido[] contenido, int pos) {
            return base.Channel.SaveDocumentTestAsync(User, Password, appId, tipeId, queryId, data, dataSet, contenido, pos);
        }
        
        public ePowerCCBApi.ePowerBridge.ResultadoAccion LoginePower(string User, string Password) {
            return base.Channel.LoginePower(User, Password);
        }
        
        public System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.ResultadoAccion> LoginePowerAsync(string User, string Password) {
            return base.Channel.LoginePowerAsync(User, Password);
        }
        
        public ePowerCCBApi.ePowerBridge.ResultadoAccion LoginePowerTest(string User, string Password) {
            return base.Channel.LoginePowerTest(User, Password);
        }
        
        public System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.ResultadoAccion> LoginePowerTestAsync(string User, string Password) {
            return base.Channel.LoginePowerTestAsync(User, Password);
        }
        
        public ePowerCCBApi.ePowerBridge.Resultado[] QueryDocument(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data) {
            return base.Channel.QueryDocument(User, Password, appId, tipeId, queryId, data);
        }
        
        public System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.Resultado[]> QueryDocumentAsync(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data) {
            return base.Channel.QueryDocumentAsync(User, Password, appId, tipeId, queryId, data);
        }
        
        public ePowerCCBApi.ePowerBridge.Resultado[] QueryDocumentTest(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data) {
            return base.Channel.QueryDocumentTest(User, Password, appId, tipeId, queryId, data);
        }
        
        public System.Threading.Tasks.Task<ePowerCCBApi.ePowerBridge.Resultado[]> QueryDocumentTestAsync(string User, string Password, int appId, int tipeId, int queryId, ePowerCCBApi.ePowerBridge.Datos[] data) {
            return base.Channel.QueryDocumentTestAsync(User, Password, appId, tipeId, queryId, data);
        }
    }
}
